### ISSUE TITLE
Instagram module not working...

### ISSUE THREAD

**Issue by karargaht** [Xtraball/SiberianCMS#2]
"The name entered is not a valid Instagram user." gives the warning.

but the user name is correct and Instagram API Keys OK.

![instagram](https://cloud.githubusercontent.com/assets/8930862/15362666/aadf035e-1d1e-11e6-8e24-1667687da16e.png)

**Comment by arttex** [comment]
Same.

**Comment by SiberianCMS** [comment]
Fixed in 4.2.0

**Comment by Simonia** [comment]
Still not working, and Im running the latest version of Siberian.

**Comment by Simonia** [comment]
Can anyone help? My issues is the excact same and Ive also got my APIS correct..
