### ISSUE TITLE
Previewer App - Revert 

### ISSUE THREAD

**Issue by krypt3d** [Xtraball/SiberianCMS#316]
Hey I think we should go back to the old way the previewer app was set up in terms of not having the message on each page saying "Tap twice to go back to apps list"

This is because some of us like to use the previewer app to create mockups for our clients to see a visualization of the app. As well, we use these photo mockups for the app stores when submitting application.

I do realize there is the new screenshot generator module but I prefer my method as it gives me high quality vector mockups of iphones and android devices and it works great for me. Please see photo for what I mean. I would highly appreciate if this change can be reverted.

![img_1466_iphone7plussilver_portrait](https://user-images.githubusercontent.com/25313885/26865470-20aedf3a-4b1a-11e7-8ce1-f5e72b80caa2.png)

**Comment by rivman** [comment]
The bug appeared since last update. The message should go away after 2 seconds but now isn't the case. 
Hope some update soon, taking screenshots from mac Xcode phone simulator is a pain in the neck. Thank you !

**Comment by SiberianCMS** [comment]
This should be fixed in 4.11.5
Thanks for the report.

**Comment by krypt3d** [comment]
Thank you kindly to both of you for the update regarding this matter. I appreciate it.

**Comment by krypt3d** [comment]
Any new update? 4.11.5 has already been released while back but the message still persists.

**Comment by rivman** [comment]
4.12 is out already. Can you please just remove the message "tap twice..." and maybe make some in-app help page to explain this app Previewer tip? 
Thank you. 

![img_8506](https://user-images.githubusercontent.com/11364533/28489750-e38b12f2-6eca-11e7-92d6-31682d83cdc2.PNG)

**Comment by Slicit** [comment]
Try to rebuild your previewer, this issue is fixed.
