### ISSUE TITLE
Chat module Push notifications displaying random characters 

### ISSUE THREAD

**Issue by theeugenegroup** [Xtraball/SiberianCMS#335]
Sine the upgrade to version 1.4 of the chat module the push notifications sent to a user when the app isn't running display random characters, see first image image.

Once the user opens the app the push the push notifications are displayed correctly , see second image.

In the back office you will (image 3) the messages, it is also displaying my server time not may local time
![image 1](https://user-images.githubusercontent.com/8466469/27773581-25bd2610-5f3a-11e7-8572-d362e439c47b.PNG)
![image 2](https://user-images.githubusercontent.com/8466469/27773582-25d2c006-5f3a-11e7-9820-1da6a2161b34.PNG)
<img width="1277" alt="screen shot 2017-07-02 at 3 19 33 pm" src="https://user-images.githubusercontent.com/8466469/27773586-3c5e5d12-5f3a-11e7-8bf2-09863bedde05.png">

**Comment by PofMagicfingers** [comment]
Please update the chatrooms to 1.4.1 found in your purchases. Issue has been fixed a few days ago.

**Comment by theeugenegroup** [comment]
The Push message is better but the time is still wrong.

My test message was sent at 5:42 MDT from my devices but it shows as 4:42 on my device and the CMS shows it was created 2 hours before it was sent.
<img width="1244" alt="screen shot 2017-07-03 at 5 46 00 am" src="https://user-images.githubusercontent.com/8466469/27791675-79d3df4a-5fb3-11e7-8a15-a07dffccb947.png">
