### ISSUE TITLE
#824-55: [Plesk] [1017] This feature is not supported for protocol version 1.6.3.0.

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#588]
Cannot upload new SSL - according to Plesk -  the cause is

Starting with Plesk Onyx 17.8, the support for outdated versions of the XML API protocol, such as 1.6.3.0, has been removed.

The error I get when trying to renew the SSL is the title of this message. Please advise. thanks a lot.

**Comment by bluesnap-rock** [comment]
I changed the packet version on
InstallCertificate.php
ListCertificates.php
DeleteCertificate.php

to

<packet version="1.6.9.1">

This worked and the renew worked - however, not sure I have done the right thing so I have switched it back to the oriignal

1.6.3.0

**Comment by LikoV2** [comment]
Fixed in 4.14.7

**Comment by bluesnap-rock** [comment]
@LikoV2  I am still having this issue on v PE - v4.14.13 still receiving the same error above.
??

**Comment by bluesnap-rock** [comment]
@LikoV2 
I had to change the packet version again on all three files in /lib/plesk/ssl to 1.6.9.1 - ?? and it worked - shall I leave this like this?

**Comment by bluesnap-rock** [comment]
OK thanks @LikoV2

**Comment by Slicit** [comment]
We found a solution, should be inside an update soon.

**Comment by Slicit** [comment]
4.15.3 will address this issue, and is scheduled for Monday 29, Oct.
