### ISSUE TITLE
Video Module: YouTube Component Sorts Videos In Wrong Order

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#97]
The YouTube component of the Video Module lists the oldest videos first.  So if the YouTube Channel have a lot of videos, the app user have to do a lot of scrolling just to get to the most recent video.  This is not user friendly.

The videos need to be sorted so that the newest videos are at the top.

**Comment by clifton11221** [comment]
I believe this is a relatively simple fix to implement so hopefully it can be fixed soon :-)

**Comment by SiberianCMS** [comment]
Fixed in 4.7.3

**Comment by clifton11221** [comment]
Even though the Release Notes for version 4.7.3 states that this problem is fixed, the issue is still there.

You can test with the NBA Channel ID (UCWJ2lWNubArHWmf3FIHbfcQ) and view it on the NBA's page (https://www.youtube.com/user/NBA/videos)

For my test I used the "Channel" option in the YouTube section of the Videos module.
